/**
 * Atlassian Cloud configuration — maps personas to Atlassian accounts,
 * projects, and spaces. Generated by the bootstrapper, consumed by the simulation.
 */

import type { PersonaId } from "./simulation.js";
import type { SpaceKey } from "./confluence.js";
import { readFile } from "fs/promises";
import { join } from "path";

export interface AtlassianUserConfig {
  accountId: string;
  email: string;
  displayName: string;
  /** API token for this user — manually populated by the operator */
  apiToken: string;
}

export interface AtlassianProjectConfig {
  id: string;
  key: string;
  name: string;
  projectTypeKey: "software" | "service_desk";
}

export interface AtlassianSpaceConfig {
  id: string;
  key: string;
  name: string;
}

export interface AtlassianConfig {
  host: string;
  cloudId?: string; // Atlassian cloud instance ID (auto-discovered)
  users: Record<PersonaId, AtlassianUserConfig>;
  projects: Record<"DR" | "SUP", AtlassianProjectConfig>;
  spaces: Record<SpaceKey, AtlassianSpaceConfig>;
  bootstrapCompleted: string; // ISO 8601
}

export async function loadAtlassianConfig(): Promise<AtlassianConfig> {
  const configPath = join(process.cwd(), "atlassian-config.json");
  const data = await readFile(configPath, "utf-8");
  return JSON.parse(data) as AtlassianConfig;
}

export function validateAtlassianConfig(config: AtlassianConfig): string[] {
  const errors: string[] = [];

  const personaIds: PersonaId[] = [
    "chad", "vanessa", "tammy", "sasha", "marcus",
    "cooper", "priya", "raj", "dana", "tk",
  ];

  for (const id of personaIds) {
    const user = config.users[id];
    if (!user) {
      errors.push(`User "${id}" missing from config (run bootstrap)`);
    } else {
      if (!user.accountId) errors.push(`User "${id}" has no accountId (run bootstrap)`);
      if (!user.apiToken) errors.push(`User "${id}" has no apiToken (add manually)`);
    }
  }

  for (const key of ["DR", "SUP"] as const) {
    if (!config.projects[key]) errors.push(`Project "${key}" missing (run bootstrap)`);
  }

  for (const key of ["PROD", "ENG", "OPS", "MKT"] as const) {
    if (!config.spaces[key]) errors.push(`Space "${key}" missing (run bootstrap)`);
  }

  return errors;
}
